---
title: "Wage and Hour Division"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dolrwagehour}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Examples

The code chunks below shows how to query the Wage and Hour Division datasets available. 
For official documentation go to: https://developer.dol.gov/wage-and-hour-division/

### WHD Compliance 

```{r, eval=FALSE}
library(dolr)

# This queries WHD Compliance datasets. 
# This gets the sheet associated with retail.
kable(head(str_trunc(dol_whd(dataset = 3, sheet = 4), 10, ellipsis = "..."))[1:7])

```

### Wage and Hour Publications System 

```{r, eval=FALSE}

# This queries the Wage and Hour Publications System 
# This get the sheet associated with: PublicationsView
dol_whd(dataset = 2, sheet = 1)

```

## Datasets and Sheets


```{r, eval=TRUE, echo=FALSE}

flcf <- data.frame("Datasets" = c("1) Farm Labor Contractor and Farm Labor Contractor Employee", rep("", 1)),
"Sheets" = paste(c("1) ", "2) "), c("Farm Labor Contractors", "Farm Labor Contractor Employees")))

whps <- data.frame("Datasets" = c("2) Wage and Hour Publications System", rep("", 1)),
"Sheets" = paste(c("1) ", "2) "), c("PublicationsView", "DocumentsView")))

whd <- data.frame("Datasets" = c("3) WHD Compliance", rep("", 3)),
"Sheets" = paste(c("1) ", "2) ", "3)", "4)"), c("full",
                                                "foodservice",
                                                "hospitality",
                                                "retail")))

breaker <- data.frame("Datasets" = c(""), "Sheets" = c(""))
knitr::kable(do.call(rbind, list(flcf, breaker, whps, breaker, whd)), "html")
```

